//! Default config aligned with `packages/sim-core/src/defaultConfig.ts`.

use super::types::*;

pub fn default_sim_config() -> SimConfig {
    SimConfig {
        seed: 42,
        ticks: 120,
        agent_counts: [3, 6, 8, 7],
        policy: PolicyVector {
            patent_regime: PatentRegime::Weak,
            patent_duration_ticks: 40,
            enforcement_intensity: 0.35,
            litigation_cost_multiplier: 1.0,
            open_science_subsidy: 0.2,
            data_sharing_mandate_strength: 0.15,
            regulatory_ambition: 0.45,
        },
        graph: GraphPreset {
            kind: GraphKind::SmallWorld,
            avg_degree: 3,
        },
        capability_beta: 0.62,
        spillover_alpha: 0.35,
        base_market_size: 220.0,
        market_growth_per_tick: 0.15,
        demand_model: DemandModel::EdgeLogit,
        edge_logit_temperature: 1.0,
        edge_logit_utility_quality: 1.0,
        edge_logit_utility_reputation: 0.02,
        edge_logit_utility_knowledge: 0.01,
        edge_logit_edge_weight_scale: 0.1,
        edge_logit_preference_noise: 0.0,
        memory_slots: 12,
        memory_decay_per_tick: 0.08,
        type_weights: [1.65, 0.85, 1.05, 0.95],
        invest_rnd_base_cost: 9.0,
        invest_rnd_cost_random_span: 3.0,
        invest_rnd_cost_per_knowledge: 0.0,
        innovation_delay_ticks: 0,
        wealth_depreciation_rate: 0.0,
        knowledge_depreciation_rate: 0.0,
        ces_quality_enabled: true,
        ces_alpha_knowledge: 0.55,
        ces_rho: -0.35,
        ces_scale: 0.14,
        ces_mix_goods: 0.52,
        ces_revenue_gamma: 0.28,
        ces_rep_relative_quality: 0.07,
        ces_rep_sales: 0.0005,
        regulatory: RegulatoryConfig {
            enabled: false,
            rule_mode: RegulatoryRuleMode::Dynamic,
            policy_scale: 1.0,
            base_stringency: 0.55,
            mitigation_efficiency: 0.65,
            victim_vulnerability: [0.55, 1.15, 1.0, 1.05],
            goods_externality_by_producer: [0.14, -0.04, 0.06, 0.09],
            services_externality_by_producer: [0.05, 0.1, -0.02, 0.04],
            externality_wealth_scale: 3.5,
            externality_reputation_scale: 0.012,
            dynamic_persistence: 0.82,
            dynamic_noise: 0.035,
            bribe: RegulatoryBribeConfig {
                enabled: true,
                base_cost: 6.0,
                detection_probability: 0.22,
                penalty_wealth: 28.0,
                penalty_reputation: 0.85,
                penalty_knowledge: 2.5,
                corruption_delta: 0.07,
                corruption_erodes_stringency: 0.55,
                corruption_reduces_detection: true,
            },
        },
        spawn: SpawnConfig {
            enabled: false,
            max_agents: 220,
            parent_cost_wealth: 32.0,
            min_parent_wealth_floor: 28.0,
            inherit_knowledge_fraction: 0.28,
            child_type_inherit: true,
            child_type: None,
            child_start_wealth: 22.0,
            link_parent_edge_weight: 0.42,
            parent_reputation_on_success: 0.05,
        },
    }
}
